#应用端口号
server:
  port: 8080
  servlet: # session有效时长为10分钟
    session:
      timeout: PT10M

#应用名称
spring:
  application:
    name: localhost
  #数据库相关配置
  datasource:
    url: jdbc:mysql://47.114.133.106:3306/gaodehan
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initial-size: 10 #连接池初始化大小
#    max-active: 30 #最大空闲数
#    min-idle: 10  #最小空闲数

  main:
    allow-bean-definition-overriding: true

  #热部署配置
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java #重启目录


#使spring能够扫描到mapper.xml
mybatis:
   mapper-locations: classpath*:mapper/*.xml
   type-aliases-package: com.dream.starting.entity
   config-location:  classpath:/mybatis-config.xml #开启mybatis在控制台的日志











