#应用端口号
server:
  port: 8096
  servlet: # session有效时长为10分钟
    session:
      timeout: PT10M

#应用名称
spring:
  application:
    name: localhost
  #数据库相关配置
  datasource:
    url: jdbc:mysql://47.114.133:3307/boot_user
    username: root
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10 #连接池初始化大小
    max-active: 30 #最大空闲数
    min-idle: 10  #最小空闲数

  main:
    allow-bean-definition-overriding: true

#elasticsearch:
#  host: 192.168.1.6
#  port: 9200

  # 设置自定义banner
#  banner:
#    location: banner.txt


  #redis配置
  redis:
    lettuce:
      pool:
        max-wait: -1s
        max-idle: 300
        min-idle: 1
      shutdown-timeout: 5s
    database: 0
    host: 47.114.133.106
    port: 6379
    password:
  session: #设置session的存储方式,采用redis存储
    store-type: redis

  #热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录


#使spring能够扫描到mapper.xml
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dream.starting.entity
  config-location:  classpath:/mybatis-config.xml #开启mybatis在控制台的日志










