package com.dream.starting.mapper;
import com.dream.starting.entity.Users;
import java.util.List;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jun 20 15:45:19 CST 2020
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jun 20 15:45:19 CST 2020
     */
    List<Users> selectAll();
}